name = "Alioune"
uuid = "91b18277-90f3-4bfc-9e7d-de8ae2faa355"
version = "1.0.0-DEV"
authors = ["Alioune Thiam <thiambada17@gmail.com > and contributors"]

[deps]
Bonito = "824d6782-a2ef-11e9-3a09-e5662e0c26f8"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
Bonito = "4.1.11"
CairoMakie = "0.15.8"
Plots = "1.41.2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
